GridLayout:
    rows: 2
    Label:
        id: time
        text: 'Kell [b]12:00[/b]'
        font_name: 'Aino'
        font_size: 120
        markup: True
    Label:
        id: temperatuur
        text: 'temperatuur'
        font_name: 'Aino'
        font_size: 80
    Label:
        id: tuul
        text: 'tuul'
        font_name: 'Aino'
        font_size: 80
    Label:
        id: suund
        text: 'suund'
        font_name: 'Aino'
        font_size: 80
